config/routes.rb
Buildcloud::Application.routes.draw do

  get '/invite/:token', to: 'invites#show', as: :invite
  put '/invite/:token', to: 'invites#update'

  
  resources :accounts do
    resources :contacts
    resources :teams
    resources :projects do
      resource :invites
      resources :worklists do
        resources :items do
          put 'complete_item'
          put 'incomplete_item'
        end
      end
      resources :issues do
        put 'close_issue'
        put 'reopen_issue'
        resources :follow_ups
      end
    end
  end

    

  resources :profiles

  resources :emails, only: [:index]

  

  devise_for :users,
             :controllers => { :registrations => "registrations" } do 
              get '/users/sign_out' => 'devise/sessions#destroy' 
  end

  resources  :users, :only => [:index] do
    member do
        put 'add_to_team'
        put 'remove_from_team'
    end
  end

  root to: 'static_pages#home'

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessible :assigned_to_id, :closed_at, :description, :title, :item_id, :issue_type, :created_by_id, :email_tokens
  belongs_to :item
  belongs_to :user, :class_name => "User", :foreign_key => 'assigned_to_id'
  belongs_to :project
  belongs_to :created_by, :class_name => "User", :foreign_key => 'created_by_id'
  validates :title, :presence => true
  validates :issue_type, :presence => true
  validates :created_by, :presence => true

  has_many :recipients, class_name: "IssueRecipient"
  has_many :users,      through: :recipients
  has_many :contacts,   through: :recipients
  has_many :follow_ups

  def self.opened
    where closed_at: nil
  end

  def self.closed
    where "closed_at IS NOT NULL"
  end

  def emails
    @emails ||= recipients.map(&:email)
  end

  def emails=(value)
    self.recipients = recipients.from_emails(Array(value), project.account )
    @emails = recipients.map(&:email)
  end

  def email_tokens=(value)
    self.emails = value.to_s.split(",").map(&:strip).uniq
  end

  def email_tokens
    emails.join(",")
  end

  def current_email_details
    recipients.map &:to_autocomplete_hash
  end

  def close!
    update_attributes closed_at: Time.now
  end

  def reopen!
    update_attributes closed_at: nil
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

	def index
		@project = current_project
		if closed_issues?
			@issues = @project.issues.closed
		else
			@issues = @project.issues.opened
		end
	end


	def show
		@project = current_project
		@issue = @project.issues.find(params[:id])
	end

	def new
		@project = current_project
	  @issue = @project.issues.build
	end

	def create
		@project = current_project
		@issue = @project.issues.build
		@issue.attributes = params[:issue]
		@issue.created_by = current_user
		unless params[:item_id].empty?
			@item = @project.items.find(params[:item_id])
			@issue.item = @item
		end

		if @issue.save
			#IssueMailer.issue_notice(@issue).deliver
			flash[:success] = "Issue successfully logged"
			redirect_to account_project_issue_path(current_account, @project, @issue)
		else
			render 'new'
		end
	end

	def edit
		@project = current_project
		@issue = @project.issues.find(params[:id]) 
	end


	def close_issue
		@project = current_project
		@issue = @project.issues.find(params[:issue_id])
		if @issue.close!
			flash[:success] = "Issue closed"
		else
			flash[:error] = "Error: could not close issue"
		end
		redirect_to :back
	end

	def reopen_issue
		@project = current_project
		@issue = @project.issues.find(params[:issue_id])
		if @issue.reopen!
			flash[:success] = "Issue reopend"
		else
			flash[:error] = "Error: could not set issue open"
		end
		redirect_to :back
	end

	def closed_issues?
		params[:filter] == 'closed'
	end

	def open_issues?
		params[:filter] != 'closed'
	end

	helper_method :closed_issues?, :open_issues?
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_error_messages.html.erb
<% if @issue.errors.any? %> 
		<div class="alert alert-error">
		<% @issue.errors.full_messages.each do |msg| %>
			Error: <%= msg %>
		<% end %>	
		</div>
<% end %>

app/views/issues/_form.html.erb
<%= form.text_field :title, :placeholder => 'Enter short description of the issue...' %>
<h3>Description/Notes</h3><br />
<%= form.text_area :description, :placeholder => 'Enter full description or notes for the issue', :rows => 5 %>

<%= form.label :email_tokens, "Who to notify:" %>
<%= form.text_field :email_tokens, "data-email-details" => form.object.current_email_details.to_json %>
<br />
<%= form.label :issue_type, "Type of issue" %>
<%= form.select :issue_type, ["RFI", "Completion of works", "Rectification", "Out of Scope", "Snag Item"] %> <br />


<div><%= form.select :assigned_to_id , @project.memberships.collect{|member| [member.user.profile.name, member.user.id]}, {:include_blank => 'Unassigned'} %></div>

app/views/issues/_issue.html.erb
<%unless issue.item.nil? %>
  <%= link_to issue.item.name, "#" %>
<% end %>
<%= link_to issue.title, [current_account, project, issue], :class => 'item-list' %>
              
<span class="label label-important"><%= issue.issue_type %></span>
<% if issue.closed_at.nil? %>
  <%= link_to 'Close', [current_account, project, issue, :close_issue], :class => 'btn btn-success btn-mini pull-right btn-gap', 
                                                       :method => 'put'%>
<% else %>
  <%= link_to 'Reopen', [current_account, project, issue, :reopen_issue], :class => 'btn btn-info btn-mini pull-right btn-gap', 
                                                       :method => 'put'%> 
 
  <% unless issue.closed_at.nil? %>
    Closed <%= relative_date(issue.closed_at) %> ago
  <% end %>
 
<% end %>                                                                                                      

<%= link_to 'Follow up', account_project_issue_follow_ups_path(current_account, project, issue), :method => :post, :class => 'btn btn-warning pull-right btn-mini btn-gap' %>
              
<div class="notes">
  <% unless title == true %>
    <% unless issue.created_by.nil? %>
     Created by <%= link_to issue.created_by.profile.name, '#' %> <%= relative_date(issue.created_at) %>
    <% end %>
  <% end %>
</div>

app/views/issues/edit.html.erb
<%= render 'error_messages' %>
<div class="row">
  <div class="span6 offset3">
    <h3> New Issue </h3><br />
    <%= form_for [current_account, @project, @issue] do |f| %>
      <%= hidden_field_tag :from, params[:from] %>
      <%= hidden_field_tag :item_id, params[:item_id] %>
      <%= render :partial => "form", :object => f %>
      <%= f.submit "Submit Issue", :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', :back, :class => 'btn'%>
    <% end %>
  </div>
</div>

app/views/issues/index.html.erb
<h3><%= link_to  @project.name, [current_account, @project] %> <i class="icon-arrow-right"></i> Issues </h3>
<hr />

<ul class="nav nav-tabs">
  <%= navbar_entry open_issues? do %>
    <%= link_to 'open', account_project_issues_path(current_account, @project) %>
  <% end %>
  <%= navbar_entry closed_issues? do %>
    <%= link_to 'closed', account_project_issues_path(current_account, @project, filter: "closed") %>
  <% end %>
  <li class="pull-right">
    <%= link_to 'New Issue', new_account_project_issue_path(current_account, @project) %>
  </li>

</ul>

<table class="table table-bordered table-condensed">
  <thead>
    <tr>
    	<th>Issues</th>
    </tr>
  </thead>
  <tbody>
    <% unless @issues.exists? %>
      <tr>
        <td>There are currently issues. Awsome!</td>
      </tr>
    <% else %>
    	<% @issues.each do |issue| %>
      <tr>
        <td>
          <%= render :partial => 'issue', :locals => { :issue => issue , :project => @project, :title => false, :open_issues => open_issues?,                                           :closed_issues => closed_issues?} %>
        </td>
      </tr>
    	<% end %>
    <% end %>
  </tbody>
</table>

app/views/issues/new.html.erb
<%= render 'error_messages' %>
<div class="row">
  <div class="span6 offset3">
    <h3> New Issue </h3><br />
    <%= form_for [current_account, @project, @issue] do |f| %>
      <%= hidden_field_tag :from, params[:from] %>
      <%= hidden_field_tag :item_id, params[:item_id] %>
      <%= render :partial => "form", :object => f %>
      <%= f.submit "Submit Issue", :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', :back, :class => 'btn'%>
    <% end %>
  </div>
</div>

app/views/issues/show.html.erb
<h3><%= link_to @project.name, [current_account, @project] %></h3>
<%= render_project_menu @project %>

  <div class="pull-right navlist"> <%= link_to [:edit,current_account, @project, @issue], :class => 'btn',
                                               :method => 'get' do %>
            <i class="icon-pencil icon-white"></i> Edit Issue
          <% end %></div>


<table class="table table-bordered table-condensed">
      <thead>
        <tr>
          <th>
            Issue 
          </th>
          
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <%= render :partial => 'issue', :locals => { :issue => @issue , :project => @project, :title => true } %> 
            <% unless @issue.description.empty? %>
              <%= @issue.description %>
            <% else %>
              No description 
            <% end %>

            <div class="notes">
                <% unless @issue.created_by.nil? %>
                  Created by <%= link_to @issue.created_by.profile.name, '#' %> <%= relative_date(@issue.created_at) %>
                <% end %>
                <% unless @issue.item.nil? %>
                  To-do <%= link_to @issue.item.name, [current_account, @project, @issue.item.worklist, @issue.item] %>
                <% end %>
              </div>
          </td>
        </tr>

      </tbody>


  </table>
  <% if (count = @issue.follow_ups.count).nonzero? %>      
  <table class="table table-bordered table-condensed">
      <thead>
        <tr>
          <th>
            Follow ups <span class="badge"><%= count %></span>
          </th>
          
        </tr>
      </thead>
      <tbody>
        <% @issue.follow_ups.each do |follow_up| %>
        <tr>
          <td>
            <% unless follow_up.followed_up_by.nil? %>
              by <%= link_to follow_up.followed_up_by.profile.name, '#' %> on 
            <% end %>
            <span class="date"><%= l follow_up.created_at, format: :short  %></span> <%= relative_date(follow_up.created_at) %> ago
          </td>
        </tr>
        <% end %>
      </tbody>
  </table>
  <% end %>