config/routes.rb
Buildcloud::Application.routes.draw do

  get '/invite/:token', to: 'invites#show', as: :invite
  put '/invite/:token', to: 'invites#update'

  
  resources :accounts do
    resources :contacts
    resources :teams
    resources :projects do
      resource :invites
      resources :worklists do
        resources :items do
          put 'complete_item'
          put 'incomplete_item'
        end
      end
      resources :issues do
        put 'close_issue'
        put 'reopen_issue'
        resources :follow_ups
      end
    end
  end

    

  resources :profiles

  resources :emails, only: [:index]

  

  devise_for :users,
             :controllers => { :registrations => "registrations" } do 
              get '/users/sign_out' => 'devise/sessions#destroy' 
  end

  resources  :users, :only => [:index] do
    member do
        put 'add_to_team'
        put 'remove_from_team'
    end
  end

  root to: 'static_pages#home'

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/views/shared/_error_messages.html.erb
<% if action.errors.any? %> 
	<div class="alert alert-error">
		<% @item.errors.full_messages.each do |msg| %>
			Error: <%= msg %>
		<% end %>	
	</div>
<% end %>

app/views/shared/_menu.html.erb
<div class="project-nav">
  <ul class="nav nav-tabs ">
    <li>
      <%= link_to account_project_worklists_path(current_account, project) do %>
        Item Lists
        <% if (count = project.items.incomplete.count).nonzero? %>
          <span class="badge"><%= count %></span>
        <% end %>
      <% end %>
    </li>
    <li>
      <%= link_to account_project_issues_path(current_account, project) do %>
        Issues
        <% if (count = project.issues.opened.count).nonzero? %>
          <span class="badge"><%= count %></span>
        <% end %>
      <% end %>
    </li>
  </ul>
</div>

app/views/shared/_notice.html.erb
<% flash.each do |key, value| %>
		<%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>