config/routes.rb
Buildcloud::Application.routes.draw do

  get '/invite/:token', to: 'invites#show', as: :invite
  put '/invite/:token', to: 'invites#update'

  
  resources :accounts do
    resources :contacts
    resources :teams
    resources :projects do
      resource :invites
      resources :worklists do
        resources :items do
          put 'complete_item'
          put 'incomplete_item'
        end
      end
      resources :issues do
        put 'close_issue'
        put 'reopen_issue'
        resources :follow_ups
      end
    end
  end

    

  resources :profiles

  resources :emails, only: [:index]

  

  devise_for :users,
             :controllers => { :registrations => "registrations" } do 
              get '/users/sign_out' => 'devise/sessions#destroy' 
  end

  resources  :users, :only => [:index] do
    member do
        put 'add_to_team'
        put 'remove_from_team'
    end
  end

  root to: 'static_pages#home'

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/project.rb
class Project < ActiveRecord::Base

  attr_accessible :created_by, :job_number, :name

  belongs_to :account

  has_many :worklists, :dependent => :destroy
  has_many :items,     :through => :worklists
  has_many :issues
  has_many :invites
   

  include Membership::HasMembersMixin

  def self.directly_accessible_by(user)
    # arel_table[:owner_id].eq(user.id)
    # user.team_ids.presence && arel_table[:team_id].in(user.team_ids)
  end

  

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_filter :authenticate_user!
	respond_to :html

	def index
		@projects = current_account.projects.all
	end

	def show
		@project   = current_projects.find(params[:id])
		@worklists = @project.worklists
	end

	def new
		@account = current_account
		@project = @account.projects.build
	end

	def create
		@account = current_account
		@project = @account.projects.build(params[:project])
		if @project.save
			@project.give_user_access(current_user)
			flash[:success] = "Added new project #{@project.name}"
			redirect_to [current_account, @project]
		else
			render 'new'
		end
	end


	def edit
		@project = current_projects.find(params[:id])
		respond_with @project
	end

	def update
		@project = current_projects.find(params[:id])
		if @project.update_attributes(params[:project])
			flash[:success] = "project sucessfully updated"
			redirect_to account_projects_path(current_account)
		else
			flash[:error] = "project failed to update"
			render 'edit'
		end
	end

	def destroy
		current_projects.find(params[:id]).destroy
		flash[:success] = "Project deleted."
  		redirect_to [current_account, @project]
	end

	def invite
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def render_project_menu(project)
    render partial: 'shared/menu', locals: {project: project}
  end

  

end

app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<div class="row">
  	<div class="span4 offset4">
  	<div class="well">
  	<%= form_for [current_account, @project] do |f| %>

  	<%= f.text_field :name, :placeholder => 'Enter Project Name' %>
    
    
    <%= f.text_field :job_number, :placeholder => 'Enter Job Number' %>
	</div>
	
  <%= f.submit "Update Project", :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', account_projects_path(current_account), :class => 'btn' %>

<% end %>

 </div>
</div>

app/views/projects/index.html.erb
<table class="table table-bordered table-condensed">
  <thead>
    <tr>
    	<th>Projects
    	
    		<%= link_to new_account_project_path(current_account), :class => 'pull-right' do %>
        <i class="icon-plus icon-white"></i> New Project
        <% end %>
    	</th>
    </tr>
  </thead>
  <tbody>
    <% unless @projects.empty? %>
      <% @projects.each do |project| %>
        <tr>
          <td><%= link_to project.name, account_project_path(current_account, project) %>
        
        
           
        	 <%= link_to edit_account_project_path(current_account, project), :class => 'pull-right', :method => 'get' do %>
             <i class="icon-pencil icon-white"></i> edit
            <% end %>
          
          </td>
        </tr>
      <% end %>
    <% else %>

      <tr>
        <td>There are currently no projects.</td>
        
      </tr>
  
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h2>New Project</h2>
 <div class="row">
  	<div class="span4 offset4">
  	<div class="well">
  	<%= form_for [@account, @project] do |f| %>


  	<%= f.text_field :name, :placeholder => 'Enter Project Name' %>
    
    
    <%= f.text_field :job_number, :placeholder => 'Enter Job Number' %>
	</div>
	
  <%= f.submit "Create Project", :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', account_projects_path(current_account), :class => 'btn' %>

<% end %>

 </div>
</div>

app/views/projects/show.html.erb
<h3><%= @project.name %></h3><span class="pull right"><%= link_to 'Invite more users', new_account_project_invites_path(current_account, @project) %></span>

<%= render_project_menu @project %>
<div class="navlist">
   Lists <%= link_to 'Add list', new_account_project_worklist_path(current_account, @project), :class => 'btn btn-mini' %>
</div>

<%= render_worklists @project.worklists %>