config/routes.rb
Buildcloud::Application.routes.draw do

  get '/invite/:token', to: 'invites#show', as: :invite
  put '/invite/:token', to: 'invites#update'

  
  resources :accounts do
    resources :contacts
    resources :teams
    resources :projects do
      resource :invites
      resources :worklists do
        resources :items do
          put 'complete_item'
          put 'incomplete_item'
        end
      end
      resources :issues do
        put 'close_issue'
        put 'reopen_issue'
        resources :follow_ups
      end
    end
  end

    

  resources :profiles

  resources :emails, only: [:index]

  

  devise_for :users,
             :controllers => { :registrations => "registrations" } do 
              get '/users/sign_out' => 'devise/sessions#destroy' 
  end

  resources  :users, :only => [:index] do
    member do
        put 'add_to_team'
        put 'remove_from_team'
    end
  end

  root to: 'static_pages#home'

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/worklist.rb
class Worklist < ActiveRecord::Base
  attr_accessible :end_date, :name, :start_date
  belongs_to :project

  has_many :items

  validates :name, :presence => true


  validate :ensure_usable_date_entry

  def ensure_usable_date_entry
  	if start_date? && !end_date?
  		errors.add :start_date, "Cannot enter a start date without a completion date"
  	else
  		ensure_has_valid_date_range
  	end
  end

  def ensure_has_valid_date_range
    if start_date? && end_date? && start_date >= end_date
      errors.add :start_date, "must occur before the end date"
    end
  end

end

app/controllers/worklists_controller.rb
class WorklistsController < ApplicationController
	respond_to :html

	def index
		@project = current_project
		@worklists = current_worklists.all
	end

	def show
		@project = current_project
		@worklist = current_worklists.find(params[:id])
		if completed_items?
			@items = @worklist.items.completed
		else
			@items = @worklist.items.incomplete
		end
	end

	def new
		@worklist = current_worklists.build
	end

	def create
		@worklist = current_worklists.build(params[:worklist])
		if @worklist.save
			flash[:success] = "Added new worklist #{@worklist.name} created"
			redirect_to [current_account, current_project]
		else
			render 'new'
		end
	end

	def edit
		@worklist = current_worklists.find(params[:id])
		respond_with @worklist
	end

	def update
		@worklist = current_worklists.find(params[:id])
		if @worklist.update_attributes(params[:worklist])
			flash[:success] = "List sucessfully updated"
			redirect_to [current_account, @worklist.project, @worklist]
		else
			flash[:error] = "List failed to update"
			render 'edit'
		end
	end

	def destroy
		current_worklists.find(params[:id]).destroy
		flash[:success] = "List deleted."
		redirect_to current_project
	end

	def completed_items?
		params[:filter] == 'completed'
	end

	def active_items?
		params[:filter] != 'completed'
	end

	helper_method :completed_items?, :active_items?

end

app/helpers/worklists_helper.rb
module WorklistsHelper

def formatted_worklist_end_date(worklist)
    date          = worklist.end_date
    duration_text = relative_date(date, Time.now.to_date)
    output        = ActiveSupport::SafeBuffer.new
    if date.future?
      output << content_tag(:span, duration_text, :class => "date")
      output << " Until schedule completion date"
    else
      output << "Was due for completion"
      output << content_tag(:span, duration_text, :class => "date overdue")
      output << " ago"
    end
    output
  end

  

  def render_worklists(worklists)
  	render partial: 'worklists/worklists', locals: {worklists: worklists}
  end

end

app/views/worklists/_error_messages.html.erb
<% if @worklist.errors.any? %> 
		<div class="alert alert-error">
		<% @worklist.errors.full_messages.each do |msg| %>
			Error: <%= msg %>
		<% end %>	
		</div>
<% end %>

app/views/worklists/_form.html.erb
<%= hidden_field_tag :from, params[:from] %>
<div class='well'>
  <%= form.text_field :name, :placeholder => 'Enter List Name' %>
</div>

<h3>Options</h3><br />
<div class='well'>

  <%= form.label 'Start date' %>
  <div>
    <%= form.date_select :start_date, {:prompt => {:day => 'Day', :month => 'Month', :year => 'Year'}}, 
                         :class => 'date-field' %>
  </div>

  <%= form.label 'Due Date' %>
  <div>
    <%= form.date_select :end_date, {:prompt => {:day => 'Day', :month => 'Month', :year => 'Year'}}, 
                          :class => 'date-field' %>
  </div>
</div>

app/views/worklists/_list_header.html.erb
<% completed_items ||= false %>
<% active_items ||= false %>
<% if completed_items %>
  <%=link_to "#{worklist.name}", [current_account, @project, worklist], :class => 'item-list' %>
<% elsif active_items %>
  <%=link_to "#{worklist.name}", [current_account, @project, worklist], :class => 'item-list' %>
<% else %>
  <%=link_to worklist.name, [current_account, @project, worklist], :class => 'item-list' %>
<% end %>

<div class='pull-right'>
    <% if worklist.start_date? && worklist.start_date.future? %>
      	Due to start in: <span class="date"><%= relative_date(worklist.start_date) %> </span>
        Duration: <span class="date"><%= relative_date(worklist.end_date, worklist.start_date) %></span>
    <% elsif worklist.end_date? %>
          <%= formatted_worklist_end_date worklist %>
    <% end %>
</div>

app/views/worklists/_worklists.html.erb
<% worklists.each do |worklist| %>
<table class="table table-bordered table-condensed">
  <thead>
    <tr>
    	<th>
       <%= render :partial => 'worklists/list_header', :locals => { :worklist => worklist } %>
      </th>
     </tr>
  </thead>
  <tbody>
    <% if worklist.items.none? %>
      <tr>
        <td>
          Let's get started and add some items to the list
        </td>
      </tr>
    <% elsif worklist.items.incomplete.none? %>
      <tr>
        <td>
          All items have been completed, why not add some more?
        </td>
      </tr>
    <% else %>
      <% worklist.items.incomplete.each do |item| %>
        <tr>
          <td>
            <%= render :partial => 'items/item', :locals => { :worklist => worklist,
                                                              :item => item,
                                                              :project => @project } %>
          </td>
        </tr>
      <% end %>
    <% end %>
    <tr>
      <td>
        <%= link_to new_account_project_worklist_item_path(current_account, @project, worklist, :from => controller.controller_name )  do%>
          <i class="icon-plus"></i> Add Item
        <% end %>
      </td>
    </tr>
  </tbody>
</table>
<br />
<% end %>

app/views/worklists/edit.html.erb
<%= render 'error_messages' %>
<div class="row">
  <div class="span4 offset4">
    <h3>Edit List</h3><br/>
    <%= form_for [current_account, @worklist.project, @worklist] do |f| %>
    
      <%= render :partial => "form", :object => f %>
  
      <%= f.submit "Update", :class => 'btn btn-primary' %>
    
      <%= link_to [current_account, @worklist.project, @worklist] , method: :delete, :class => 'btn btn-danger', confirm: "You sure?" do %>
        <i class="icon-trash icon-white"></i> Delete
      <% end %>
      <%= link_to 'Cancel', [current_account, @worklist.project, @worklist], :class => 'btn'%>
    <% end %>
  </div>
</div>

app/views/worklists/index.html.erb
<h3><%= link_to @project.name, [current_account, @project] %> <i class="icon-arrow-right"></i> Item Lists </h3>
<hr />

<div class="navlist">
  Lists <%= link_to 'Add list', new_account_project_worklist_path(current_account, @project), :class => 'btn btn-mini' %>
</div>

<%= render_worklists @worklists %>

app/views/worklists/new.html.erb
<%= render 'error_messages' %>
<div class="row">
  <div class="span4 offset4">
    <h3>New List</h3><br/>
    <%= form_for [current_account, @worklist.project, @worklist] do |f| %>

      <%= render :partial => "form", :object => f %>


      <%= f.submit "Create List", :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', [current_account, @worklist.project], :class => 'btn'%>

    <% end %>
  </div>
</div>

app/views/worklists/show.html.erb
<h3>
  <%= link_to @project.name, [current_account, @project] %>
  <i class="icon-arrow-right"></i> <%= link_to 'Item Lists', [current_account, @project, :worklists] %>
  <i class="icon-arrow-right"></i> <%= @worklist.name %>
</h3>
<hr />


<ul class="nav nav-tabs">
  <%= navbar_entry active_items? do %>
    <%= link_to 'Active', [current_account, @project, @worklist] %>
  <% end %>
  <%= navbar_entry completed_items? do %>
    <%= link_to 'Completed', account_project_worklist_path(current_account, @project, @worklist, filter: "completed") %>
  <% end %>

  <li class="pull-right">
    <%= link_to [:edit, current_account, @project, @worklist], :method => 'get' do %>
      <i class="icon-pencil icon-white"></i> Edit List
    <% end %>
  </li>
</ul>

<table class="table table-bordered table-condensed">
  <thead>
    <tr>
      <th>
        <%= render :partial => 'worklists/list_header', :locals => { :worklist => @worklist, completed_items: completed_items?, active_items: active_items? } %>
      </th>
     </tr>
  </thead>
  <tbody>
    <% if !@worklist.items.exists? %>
      <tr>
        <td>
          Let's get started and add some tasks to the list
        </td>
      </tr>
    <% elsif !@worklist.items.incomplete.exists? %>
      <tr>
        <td>
          All items have been completed, why not add some more?
        </td>
      </tr>
    <% else %>
      <% @items.each do |item| %>
        <tr>
          <td>
            <%= render :partial => 'items/item', :locals => { :worklist => @worklist,
                                                              :item => item,
                                                              :project => @project } %>
          </td>
        </tr>
      <% end %>
    <% end %>
    <tr>
      <td>
        <%= link_to [:new,current_account, @project, @worklist, :item]  do%>
          <i class="icon-plus"></i> Add to-do
        <% end %>
      </td>
    </tr>
  </tbody>
</table>
<br />